apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smarthr360-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  tls:
    - hosts:
        - dev.smarthr360.com
        - api.dev.smarthr360.com
      secretName: smarthr360-dev-tls
  rules:
    - host: api.dev.smarthr360.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: smarthr360-api
                port:
                  number: 8000
    - host: dev.smarthr360.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: smarthr360-api
                port:
                  number: 8000
