apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smarthr360-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rate-limit: "100"
spec:
  tls:
    - hosts:
        - staging.smarthr360.com
        - api.staging.smarthr360.com
      secretName: smarthr360-staging-tls
  rules:
    - host: api.staging.smarthr360.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: smarthr360-api
                port:
                  number: 8000
    - host: staging.smarthr360.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: smarthr360-api
                port:
                  number: 8000
